version: 2
jobs:
  build:
    working_directory: ~/dockr
    docker:
      - image: rayriffy/php:alpine
    steps:
      - checkout
      - run:
          name: Check PHP version
          command: php -v
      - run:
          name: Install composer
          command: |
            mkdir ~/phplint
            cd ~/phplint
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: composer
          command: |
            cd ~/phplint
            php composer.phar require --dev jakub-onderka/php-parallel-lint
            php composer.phar require --dev jakub-onderka/php-console-highlighter
      - run:
          name: Test Files
          command: |
            cd ~/phplint
            ./vendor/bin/parallel-lint ~/dockr/*
      - store_artifacts:
          path: ~/dockr
      - store_artifacts:
          path: ~/phplint
  deploy:
    machine:
        enabled: true
    working_directory: ~/dockr
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c7:29:52:e0:f0:33:ca:91:1b:30:3a:96:1f:34:a7:fd"
      - run:
          name: Zipping files
          command: cd ~/dockr && zip -r ~/dockr_deploy.zip *
      - run:
          name: Deploy to Server
          command: |
            scp -C -i ~/.ssh/id_rsa_c72952e0f033ca911b303a961f34a7fd -r ~/dockr_deploy.zip circleci@deploy.rayriffy.com:~/landing/dockr_deploy.zip
            ssh -i ~/.ssh/id_rsa_c72952e0f033ca911b303a961f34a7fd circleci@deploy.rayriffy.com 'rm -rf ~/production/dockr.rayriffy.com/* && unzip ~/landing/dockr_deploy.zip -d ~/production/dockr.rayriffy.com && rm -rf ~/landing/dockr_deploy.zip'
      - store_artifacts:
          path: ~/dockr_deploy.zip
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master